image: node:18

stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm ci
    - npm run build --if-present
    - npm test
    - npm run codecov
  artifacts:
    paths:
      - coverage/