# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./

# Using npm ci with ignore-scripts to avoid unwanted prepare script, then build explicitly
# If pnpm-lock.yaml exists, consider installing via npm
RUN npm install --ignore-scripts || true

# Copy the rest of the application
COPY . .

# Build the app
RUN npm run build

# Expose any ports if necessary, though MCP uses stdio

# Set the default command to run the MCP server
CMD ["node", "dist/index.js"]
