# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-bullseye

# 安装 Chrome 和 Puppeteer 所需的依赖项 (Install Chrome and Puppeteer dependencies)
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# 设置 Puppeteer 环境变量 (Set Puppeteer environment variables)
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./

# Install dependencies and allow prepare script to run
RUN npm install

# Copy the rest of the application
COPY . .

# Expose any ports if necessary, though MCP uses stdio

# Set the default command to run the MCP server
CMD ["node", "dist/index.js"]
